name: stylestack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Estado
  provider: ^6.0.5

  # API
  http: ^1.2.0

  # IDs únicos
  uuid: ^4.0.0

  # Persistencia local
  shared_preferences: ^2.2.2

  # Cámara / galería
  camera: ^0.10.5+5
  image_picker: ^1.0.4

  # Archivos
  path_provider: ^2.1.1

  # Vibración
  vibration: ^3.1.8

  # Sensores
  sensors_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  geolocator: ^10.1.0
  flutter pub get
  